"""Small fixture pipeline for multi-environment reproducibility verification.

Reads a fixture C source tree through SourceTree, builds dict/set-heavy data
structures, and writes generated artifacts through OutputRoot.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

from ectt.core.determinism import Clock, FixedClock, canonical_text, stable_id
from ectt.core.fs import OutputRoot, SourceTree

FUNC_DECL_RE = re.compile(r"^\s*(?:[A-Za-z0-9_]+\s+)+([A-Za-z0-9_]+)\s*\(([^)]*)\)\s*;", re.MULTILINE)
INCLUDE_RE = re.compile(r'^\s*#include\s*["<]([^">]+)[">]', re.MULTILINE)


def run_pipeline(
    source_dir: Path | str,
    output_dir: Path | str,
    clock: Clock | None = None,
) -> dict[str, str]:
    """Execute the pipeline from source_dir to output_dir and return the output manifest."""
    source_tree = SourceTree(source_dir)
    output_root = OutputRoot(output_dir, source_roots=[source_dir])

    if clock is None:
        clock = FixedClock("2026-09-26T12:00:00+00:00")

    # Read C source files through the read-only guard
    found_functions: set[str] = set()
    found_includes: set[str] = set()
    file_digests: dict[str, str] = {}
    test_cases: list[dict[str, Any]] = []

    for rel_path in source_tree.walk_files():
        posix_path = rel_path.as_posix()
        content = source_tree.read_text(rel_path)
        file_digests[posix_path] = stable_id(content)

        # Extract includes
        for inc in INCLUDE_RE.findall(content):
            found_includes.add(inc)

        # Extract functions
        for func_name, params in FUNC_DECL_RE.findall(content):
            found_functions.add(func_name)
            func_id = stable_id(posix_path, func_name)
            test_cases.append(
                {
                    "func_name": func_name,
                    "file": posix_path,
                    "id": func_id,
                    "params": [p.strip() for p in params.split(",") if p.strip()],
                    "test_floats": [0.1, 1e-7, -0.0, 3.14159],
                    "tags": {"autogen", "c-unit", "deterministic", func_name},
                }
            )

    # Build dict/set-heavy data with deliberate non-canonical initial ordering
    # to exercise canonical_json's key and set sorting
    analysis_model = {
        "zeta_metric": 99.9,
        "alpha_version": "1.0",
        "timestamp": clock.isoformat(),
        "source_files": file_digests,
        "all_functions": found_functions,  # raw set
        "all_includes": found_includes,    # raw set
        "tolerances": {
            "low": 1e-7,
            "zero_neg": -0.0,
            "nominal": 0.1,
        },
    }

    # Write artifacts through OutputRoot
    # 1. Analysis model JSON
    output_root.write_json("models/analysis_model.json", analysis_model)

    # 2. Test cases JSON
    output_root.write_json("tests/generated_tests.json", test_cases)

    # 3. Generated C stub file
    stub_lines = [
        "/* Generated by ECTT test harness generator */",
        f"/* Generated at: {clock.isoformat()} */",
        "",
    ]
    for inc in sorted(found_includes):
        stub_lines.append(f'#include "{inc}"')
    stub_lines.append("")
    for func in sorted(found_functions):
        stub_lines.append(f"void stub_{func}(void) {{")
        stub_lines.append(f'    /* Stub implementation for {func} */')
        stub_lines.append("}")
        stub_lines.append("")
    stub_content = canonical_text("\n".join(stub_lines))
    output_root.write_text("generated/stubs.c", stub_content)

    # 4. Summary text file
    summary_text = (
        f"Summary Report\n"
        f"Timestamp: {clock.isoformat()}\n"
        f"Total functions: {len(found_functions)}\n"
        f"Total includes: {len(found_includes)}\n"
    )
    output_root.write_text("reports/summary.txt", summary_text)

    return output_root.manifest()


def main() -> None:
    parser = argparse.ArgumentParser(description="ECTT Fixture Pipeline Runner")
    parser.add_argument("--source-dir", required=True, type=Path, help="Path to source root")
    parser.add_argument("--output-dir", required=True, type=Path, help="Path to output root")
    parser.add_argument("--clock-iso", default="2026-09-26T12:00:00+00:00", help="Fixed clock timestamp")
    args = parser.parse_args()

    clock = FixedClock(args.clock_iso)
    manifest = run_pipeline(args.source_dir, args.output_dir, clock=clock)
    print(f"Pipeline executed successfully. Total generated files: {len(manifest)}")


if __name__ == "__main__":
    main()
